/**
 * `derive:` — the target's one command that regenerates derived files where
 * their inputs are final: in the composed merge, after the gitlinks have been
 * settled and before anything is verified.
 *
 * A generated file whose inputs are the root's gitlinks at the merged commit
 * cannot be regenerated by an author, who does not know the merge result; two
 * honest changes then conflict on it, or the check that compares it sends one
 * of them back for a file it does not own. The queue is the only place those
 * inputs are final, so the queue regenerates (hh 27176, @cto 11a346da).
 *
 * The command runs in the merged worktree with the check environment
 * (`YRD_REPO`, `YRD_CANDIDATE_SHA`, `YRD_BASE_SHA`, the built base) and the
 * check bound. Exit 0 and a clean tree: nothing was derived, the composed merge
 * is the candidate. Exit 0 and changes inside one or more submodules: each
 * changed submodule is committed on its settled pin as one commit whose
 * subject is the command's first non-empty output line, the new pins are
 * carried by one root commit on the target, and that carrier is composed into
 * the merge by the same `git super merge`, so the candidate is again a
 * two-parent merge that freezes its own publication intent. Any other exit, a
 * change outside a submodule, or a command that is not there stops the
 * compose by name: the change is stuck, the queue's, never the submitter's.
 */
import { join } from "node:path"
import type { Process } from "@yrd/process"
import { composeGitlinkCarrier } from "git-super/gitlink-carrier"
import { checkLogPath, DEFAULT_CHECK_BOUND_MS, runCheck, type CheckResult } from "./check.ts"
import { gitIn, resolveGitSelection, type GitInvocationOptions, type GitSelection } from "./git.ts"

/** The name the derive runs, logs and ends a change under. */
export const DERIVE = "derive"

/** The target's `derive:`, with the places its one run needs. */
export type DeriveSpec = Readonly<{
  /** The declaration's `derive:`: one shell command, as a check's `run:` is. */
  run: string
  /** Where the derive's log goes, the check logs' own directory. */
  logDir: string
  /** The temp root the derive gets as `TMPDIR`, as a check does. */
  tmpdir: string
  /** The bound; the check default unless the caller says otherwise. */
  timeoutMs?: number
}>

/** What one derive did to the composed merge. */
export type Derived = Readonly<{
  /** The commit subject the command printed, used on every derived commit. */
  subject: string
  /** Each submodule the command changed, with the pin it stood at and the commit made on it. */
  submodules: readonly Readonly<{ path: string; from: string; to: string }>[]
  /** The one root commit on the target that carries the new pins. */
  carrier: string
  /** The command's own run. */
  ran: Readonly<{ result: CheckResult; start: string; end: string }>
}>

export class DeriveFailed extends Error {
  constructor(
    readonly commit: string,
    readonly why: string,
    readonly ran?: Readonly<{ result: CheckResult; start: string; end: string }>,
  ) {
    super(`derive stopped the compose of ${commit.slice(0, 12)}: ${why}`)
    this.name = "DeriveFailed"
  }
}

export type DeriveInWorktree = Readonly<{
  /** The merged worktree: HEAD is the composed merge, its submodules settled at the merged pins. */
  cwd: string
  /** The queue clone the worktree belongs to (its Git selection is resolved there). */
  repo: string
  /** The composed merge the worktree stands at. */
  candidate: string
  /** The target the merge was composed onto; the carrier's parent. */
  targetHead: string
  derive: DeriveSpec
  process?: Process
  env?: NodeJS.ProcessEnv
  selection?: GitSelection
  gitOptions?: GitInvocationOptions
  hooksPath?: string
  queueRun?: boolean
}>

/**
 * Run the target's `derive:` in the merged worktree. Returns `undefined` when
 * the command changed nothing, the derived pins and carrier when it did, and
 * throws `DeriveFailed` for everything else. The caller composes the carrier
 * into the merge; this never writes a merge commit.
 */
export async function deriveInWorktree(options: DeriveInWorktree): Promise<Derived | undefined> {
  const { cwd, candidate, derive } = options
  const start = new Date().toISOString()
  const result = await runCheck({
    cwd,
    env: options.env,
    queueRun: options.queueRun,
    logDir: derive.logDir,
    process: options.process,
    tmpdir: derive.tmpdir,
    spec: { name: DERIVE, run: derive.run, timeoutMs: derive.timeoutMs ?? DEFAULT_CHECK_BOUND_MS },
    tree: { candidate, base: options.targetHead },
  })
  const ran = { end: new Date().toISOString(), result, start }
  if (result.result !== "pass") {
    throw new DeriveFailed(
      candidate,
      `\`${derive.run}\` ${result.result} (exit ${String(result.exit)}${result.why === undefined ? "" : `, ${result.why}`}); log ${checkLogPath(derive.logDir, DERIVE)}`,
      ran,
    )
  }
  const selection =
    options.selection ?? (await resolveGitSelection(options.repo, { process: options.process, env: options.env }))
  const gitAt = (path: string) =>
    gitIn(path, options.process, selection, {
      ...(options.env === undefined ? {} : { env: options.env }),
      ...options.gitOptions,
    })
  const root = gitAt(cwd)
  const status = (await root(["status", "--porcelain=v1", "--untracked-files=all", "--ignore-submodules=none"])).split(
    "\n",
  )
  const changedPaths = status.filter((line) => line.trim() !== "").map((line) => line.slice(3).trim())
  if (changedPaths.length === 0) return undefined
  const gitlinks = new Set(
    (await root(["ls-files", "-s"]))
      .split("\n")
      .filter((line) => line.startsWith("160000 "))
      .map((line) => line.split("\t")[1] ?? ""),
  )
  const outside = changedPaths.filter((path) => !gitlinks.has(path))
  if (outside.length > 0) {
    throw new DeriveFailed(
      candidate,
      `\`${derive.run}\` changed ${outside.join(", ")} outside every submodule; root derivation is not admitted yet (27176 first slice): a derive may only regenerate files inside a submodule`,
      ran,
    )
  }
  const subject = await subjectOf(derive, candidate, ran)
  const submodules: Derived["submodules"][number][] = []
  for (const path of [...changedPaths].sort()) {
    const child = gitAt(join(cwd, path))
    const from = (await child(["rev-parse", "HEAD"])).trim()
    await child(["add", "-A"])
    await child([
      ...(options.hooksPath === undefined ? [] : ["-c", `core.hooksPath=${options.hooksPath}`]),
      "-c",
      "user.name=yrd",
      "-c",
      "user.email=yrd@derive",
      "commit",
      "--quiet",
      "--no-verify",
      "-m",
      subject,
    ])
    const to = (await child(["rev-parse", "HEAD"])).trim()
    if (to === from) throw new DeriveFailed(candidate, `${path} reported changes but its commit did not move`, ran)
    submodules.push({ path, from, to })
  }
  // Composed in the worktree: the derived child commits live in its submodule stores, and its root objects are the
  // queue clone's, so the carrier is reachable there for the compose that follows.
  const carrier = await composeGitlinkCarrier({
    repo: cwd,
    base: options.targetHead,
    pins: submodules.map(({ path, to }) => ({ path, commit: to })),
    message: `${subject}\n\nDerived-From: ${candidate}\n`,
  })
  return { subject, submodules, carrier: carrier.commit, ran }
}

/** The command's first non-empty output line names the derived commit; without one the paths do. */
async function subjectOf(derive: DeriveSpec, candidate: string, ran: Derived["ran"]): Promise<string> {
  const { readFile } = await import("node:fs/promises")
  const log = await readFile(checkLogPath(derive.logDir, DERIVE), "utf8").catch(() => "")
  const line = log
    .split("\n")
    .map((entry) => entry.trim())
    .find((entry) => entry !== "")
  if (line === undefined) {
    throw new DeriveFailed(
      candidate,
      `\`${derive.run}\` changed files but printed no subject line for the derived commit`,
      ran,
    )
  }
  return line.length > 200 ? `${line.slice(0, 197)}...` : line
}
