/**
 * @failure Every per-candidate assertion in this suite can pass while the queue
 * rebuilds each candidate many times to land it once. The rebuild ("recut") tax
 * is a property of the DRAIN, not of any single candidate, so a fully green
 * suite measured none of it and a ~20%-of-runs stale rate stayed invisible for
 * weeks.
 * @why Correctness tests ask "did it land"; this one asks "how many builds did
 * landing it cost". Payloads here are DISJOINT — no two candidates touch the
 * same file — so no rebuild is resolving a conflict. Every rebuild is waste.
 * @level l2
 * @consumer @yrd/queue
 *
 * ## What produces the tax
 *
 * `createBaseResolutionCycle` (src/queue.ts) resolves the base ONCE per drain
 * cycle. Every candidate composed in that cycle is therefore pinned to the same
 * base sha — but only the first can land, because landing advances the real
 * base tip. Each remaining candidate then reaches its merge step pinned to a
 * superseded base and is refused `stale-base` (production does exactly this
 * comparison at src/command.ts:7151 — the checked-out HEAD versus the run's
 * pinned `baseSha`). `queueAuthorityReleaseReason` (src/queue.ts) treats
 * `stale-base` as environmental and releases queue authority, so the PR
 * re-admits next cycle and its candidate — and its checks — are built again.
 *
 * ## Maintaining the baseline
 *
 * `MEASURED` below is a recorded measurement, not a preference. It is exact and
 * deterministic (fixed clock, seeded ids, no IO). When queue behaviour changes
 * the tax, BOTH tests here are expected to fail: re-run the drill, paste the new
 * numbers, and re-date the constant. That is the intended workflow — a census
 * instrument whose baseline drifts silently is worth nothing.
 */
import { describe, expect, it } from "vitest"
import { createBayJobDefs, withBays, type BayWorkspace } from "@yrd/bay"
import { createMemoryJournal, createYrd, createYrdDef, pipe } from "@yrd/core"
import { withJobs, type JobResult } from "@yrd/job"
import { createLogger } from "loggily"
import * as z from "zod"
import {
  candidateRefFor,
  withMerge,
  withQueue,
  withStep,
  type AddStepResult,
  type IntegrationProof,
  type ChangeShape,
  type StepExecution,
} from "@yrd/queue"

const BASE = "a".repeat(40)
const runtime = { runner: "local", leaseMs: 60_000 }

const CheckResultSchema = z.object({ checked: z.boolean() }).strict()
const ReviewResultSchema = z.object({ approved: z.boolean() }).strict()
type CheckResult = z.infer<typeof CheckResultSchema>
type ReviewResult = z.infer<typeof ReviewResultSchema>
type CheckedShape = AddStepResult<ChangeShape, "check", CheckResult>
type ReviewedShape = AddStepResult<CheckedShape, "review", ReviewResult>

function ids(initial = 0): () => string {
  let value = initial
  return () => `00000000-0000-7000-8000-${(++value).toString(16).padStart(12, "0")}`
}

function workspace(): BayWorkspace {
  const HEAD = "1".repeat(40)
  return {
    revision: "test-workspace-v1",
    provision: (input) => ({
      status: "completed",
      conclusion: "success",
      output: { path: `/repo/.bays/${input.bay}`, headSha: HEAD, baseSha: BASE },
    }),
    refresh: (input) => ({
      status: "completed",
      conclusion: "success",
      output: { path: input.path ?? `/repo/.bays/${input.bay}`, headSha: HEAD, baseSha: BASE, dirty: false },
    }),
    checkpoint: () => ({
      status: "completed",
      conclusion: "success",
      output: { headSha: HEAD, pushed: true, wip: false },
    }),
    deprovision: () => ({ status: "completed", conclusion: "success", output: {} }),
  }
}

/** A distinct 40-hex sha per logical commit, so base motion is observable. */
function sha(seed: string): string {
  let hash = 0x811c9dc5
  for (let index = 0; index < seed.length; index += 1) {
    hash = Math.imul(hash ^ seed.charCodeAt(index), 0x01000193) >>> 0
  }
  return hash.toString(16).padStart(8, "0").repeat(5)
}

type Drill = Readonly<{
  builds: number
  merges: number
  checks: number
  staleRefusals: number
  cycles: number
  integrated: number
  submitted: number
}>

/**
 * Drive `candidates` disjoint-payload PRs through a real queue until every one
 * integrates, counting the builds it took. Base motion is generated by the
 * merges themselves: each successful merge advances `head`, and a merge whose
 * run is pinned to a superseded base refuses `stale-base`.
 */
async function drainDrill(
  options: Readonly<{ candidates: number; batch: number | false; cycleBudget?: number }>,
): Promise<Drill> {
  const payloads = new Map<string, string>()
  let head = BASE
  let builds = 0
  let merges = 0
  let checks = 0
  let staleRefusals = 0

  const check = withStep(
    "check",
    (): JobResult<CheckResult> => {
      checks += 1
      return { status: "completed", conclusion: "success", output: { checked: true } }
    },
    { revision: "check-v1", output: CheckResultSchema },
  )
  const review = withStep(
    "review",
    (_input: StepExecution<CheckedShape>): JobResult<ReviewResult> => ({
      status: "completed",
      conclusion: "success",
      output: { approved: true },
    }),
    { revision: "review-v1", output: ReviewResultSchema },
  )
  const merge = withMerge(
    (input: StepExecution<ReviewedShape>): JobResult<IntegrationProof> => {
      const members = input.prs.map((pr) => pr.id)
      const pinned = input.prs[0]?.baseSha ?? BASE
      // The production staleness comparison, verbatim: a run pinned to a base
      // the branch has moved off cannot fast-forward (src/command.ts:7151).
      if (pinned !== head) {
        staleRefusals += 1
        return {
          status: "completed",
          conclusion: "failure",
          error: { code: "stale-base", message: `base moved from ${pinned} to ${head}` },
        }
      }
      const commit = sha(`landing:${merges}:${members.join(",")}`)
      head = commit
      merges += 1
      return { status: "completed", conclusion: "success", output: { commit, baseSha: commit } }
    },
    { revision: "merge-v1" },
  )

  const queue = withQueue({
    steps: [check, review, merge] as const,
    batch: options.batch,
    defaultSteps: ["check", "review", "merge"],
    resolveBaseSha: () => head,
    prepareCandidate: (input) => {
      const members = input.prs.map((pr) => (pr as { id: string }).id)
      // Disjoint payloads: no two members ever touch the same file, so every
      // rebuild counted here is pure tax and never conflict resolution.
      const touched = members.map((id) => payloads.get(id) ?? id)
      if (new Set(touched).size !== touched.length) {
        throw new Error(`yrd: drill payloads are not disjoint: ${touched.join(",")}`)
      }
      builds += 1
      const { prs: _prs, ...candidate } = input
      // Content-addressed, not id-addressed (22332): the published name has to
      // state the evidence it carries, and the queue refuses a preparer that
      // names a candidate after an id chosen before that evidence existed.
      const candidateSha = sha(`candidate:${input.id}:${input.baseSha}`)
      return {
        ...candidate,
        sha: candidateSha,
        ref: candidateRefFor(candidateSha),
        mergeability: "mergeable" as const,
      }
    },
  })

  const bayJobs = createBayJobDefs(workspace())
  const definition = queue(
    pipe(createYrdDef(), withJobs({ definitions: [bayJobs, queue.jobDefs] }), withBays({ jobs: bayJobs })),
  )
  await using app = await createYrd(definition, {
    inject: {
      journal: createMemoryJournal(),
      id: ids(),
      clock: () => "2026-01-01T00:00:00.000Z",
      log: createLogger("test", [{ level: "silent" }]),
    },
  })

  for (let index = 0; index < options.candidates; index += 1) {
    const branch = `issue/tput-${index}`
    await app.bays.submit({ branch, headSha: sha(`head:${index}`), base: "main", baseSha: BASE })
    const pr = Object.values(app.state().bays.prs).find((item) => item.branch === branch)
    if (pr === undefined) throw new Error(`yrd: drill PR for '${branch}' was not recorded`)
    payloads.set(pr.id, `file-${index}.txt`)
  }
  const submitted = payloads.size
  if (submitted !== options.candidates) {
    throw new Error(`yrd: drill submitted ${submitted} PRs, expected ${options.candidates}`)
  }

  const integratedCount = (): number =>
    Object.values(app.state().bays.prs).filter((pr) => pr.integration !== undefined).length
  const budget = options.cycleBudget ?? options.candidates * 4
  let cycles = 0
  while (cycles < budget && integratedCount() < submitted) {
    cycles += 1
    await app.queue.run({}, runtime)
  }

  return { builds, merges, checks, staleRefusals, cycles, integrated: integratedCount(), submitted }
}

type Point = Readonly<{
  candidates: number
  batch: number | false
  builds: number
  merges: number
  checks: number
  staleRefusals: number
  cycles: number
}>

/**
 * Measured 2026-08-14 against yrd main a22f2c1e, before check-transplant.
 *
 * Exact and reproducible. `merges` equals the number of batch-groups
 * G = ceil(candidates / batch); `builds` equals G(G+1)/2, so the drain rebuilds
 * every not-yet-landed group once per cycle and pays
 *
 *     builds per landing = (G + 1) / 2
 *
 * The tax is not a constant overhead — it grows in direct proportion to queue
 * depth. Ten unbatched disjoint candidates cost 55 builds and 55 checks to land
 * 10 times.
 */
const MEASURED: readonly Point[] = [
  { candidates: 8, batch: false, builds: 36, merges: 8, checks: 36, staleRefusals: 28, cycles: 8 },
  { candidates: 10, batch: false, builds: 55, merges: 10, checks: 55, staleRefusals: 45, cycles: 10 },
  { candidates: 12, batch: false, builds: 78, merges: 12, checks: 78, staleRefusals: 66, cycles: 12 },
  { candidates: 10, batch: 2, builds: 15, merges: 5, checks: 15, staleRefusals: 10, cycles: 5 },
  { candidates: 10, batch: 4, builds: 6, merges: 3, checks: 6, staleRefusals: 3, cycles: 3 },
  { candidates: 10, batch: 10, builds: 1, merges: 1, checks: 1, staleRefusals: 0, cycles: 1 },
]

/** The headline point: ten concurrent unbatched disjoint candidates. */
const HEADLINE = MEASURED[1]!

/**
 * A landing may cost at most 1.2 builds — the ~20% rebuild tax the hardening
 * program's economic claim is written against. Disjoint payloads make anything
 * above 1.0 pure waste; 1.2 leaves room for a single unavoidable base race.
 */
const RECUT_TAX_BUDGET = 1.2

// Six drills of real drain take ~2s alone but several times that under a loaded
// parallel suite; the default 5s timeout flakes. Both tests are given room —
// especially the `it.fails` one, where a timeout would otherwise COUNT AS the
// expected failure and quietly hide a broken fixture.
const DRILL_TIMEOUT_MS = 120_000

describe("queue drain throughput — rebuilds per landing", () => {
  // Green today and green after the fix, and the canary for the test below:
  // it drives the same drill, so any fixture break, timeout or environmental
  // fault turns this file red HERE, loudly and attributably. The expected-fail
  // below can therefore only be silently wrong in a world where this passes —
  // which is exactly a world where the drill is healthy and the tax is real.
  it(
    "drains every disjoint candidate and reproduces the recorded build counts",
    async () => {
      const observed: Point[] = []
      for (const point of MEASURED) {
        const drill = await drainDrill({ candidates: point.candidates, batch: point.batch })
        expect(drill.integrated, `all ${point.candidates} candidates must integrate`).toBe(drill.submitted)
        expect(drill.builds).toBeGreaterThanOrEqual(drill.merges)
        const groups = Math.ceil(point.candidates / (point.batch === false ? 1 : point.batch))
        expect(drill.merges, "one landing per batch-group").toBe(groups)
        expect(drill.builds, "G(G+1)/2 — every unlanded group rebuilt once per cycle").toBe((groups * (groups + 1)) / 2)
        observed.push({
          candidates: point.candidates,
          batch: point.batch,
          builds: drill.builds,
          merges: drill.merges,
          checks: drill.checks,
          staleRefusals: drill.staleRefusals,
          cycles: drill.cycles,
        })
      }
      expect(observed).toEqual(MEASURED)
    },
    DRILL_TIMEOUT_MS,
  )

  // EXPECTED TO FAIL until check-transplant lands. When it does, this test
  // starts passing, `it.fails` turns red, and whoever landed the fix re-records
  // MEASURED above and drops this marker — locking the win in.
  it.fails(
    "keeps rebuilds per landing within the recut-tax budget",
    async () => {
      const drill = await drainDrill({ candidates: HEADLINE.candidates, batch: HEADLINE.batch })
      const buildsPerMerge = drill.builds / drill.merges
      expect(
        buildsPerMerge,
        `${drill.builds} builds and ${drill.checks} checks to land ${drill.merges} disjoint candidates ` +
          `(${drill.staleRefusals} stale-base refusals over ${drill.cycles} cycles)`,
      ).toBeLessThanOrEqual(RECUT_TAX_BUDGET)
    },
    DRILL_TIMEOUT_MS,
  )
})
